version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: castlecare-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: castlecare
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: castlecare-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Uncomment this section if you want to use LocalStack for AWS services
  # localstack:
  #   image: localstack/localstack:latest
  #   container_name: castlecare-localstack
  #   ports:
  #     - "4566:4566"
  #   environment:
  #     - SERVICES=sqs,s3
  #     - DEBUG=1
  #     - DATA_DIR=/tmp/localstack/data
  #   volumes:
  #     - localstack-data:/tmp/localstack
  #     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres-data:
  redis-data:
  # localstack-data:
